# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Variant(models.Model):
    Chromosome_Number = models.BigIntegerField(default=0)
    Position = models.BigIntegerField(default=0)
    Var_ID = models.CharField(max_length=100, default="")
    Reference = models.CharField(max_length=100, default="")
    Alternate = models.CharField(max_length=100, default="")
    Quality = models.FloatField(max_length=100, default="")
    Filter = models.CharField(max_length=100, default="")

    def __str__(self):
        return str(self.Chromosome_Number) + ':' + str(self.Position) + ' ' + self.Reference + '/' + self.Alternate





class Population(models.Model):
    Variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    Allele_Count = models.BigIntegerField(default=0)
    AC_African_American = models.BigIntegerField(default=0)
    AC_American = models.BigIntegerField(default=0)
    AC_Adjusted = models.BigIntegerField(default=0)
    AC_East_Asian = models.BigIntegerField(default=0)
    AC_Finnish = models.BigIntegerField(default=0)
    AC_Hemizygous = models.CharField(max_length=5, default="")
    AC_Heterozygous = models.CharField(max_length=100, default="")
    AC_Homozygous = models.BigIntegerField(default=0)
    AC_Non_Finnish_European = models.BigIntegerField(default=0)
    AC_Other = models.BigIntegerField(default=0)
    AC_South_Asian = models.BigIntegerField(default=0)
    Allele_Frequency = models.CharField(max_length=60, default="")
    Allele_Number = models.BigIntegerField(default=0)
    AN_African_American = models.BigIntegerField(default=0)
    AN_American=models.BigIntegerField(default=0)
    AN_Adjusted = models.BigIntegerField(default=0)
    AN_East_Asian = models.BigIntegerField(default=0)
    AN_Finnish = models.BigIntegerField(default=0)
    AN_Non_Finnish = models.BigIntegerField(default=0)
    AN_Other = models.BigIntegerField(default=0)
    AN_South_Asian = models.BigIntegerField(default=0)
    Read_Depth = models.BigIntegerField(default=0)
    Genotype_Quality_MEAN = models.FloatField(max_length=20, default="")
    GQ_Standard_Deviation = models.FloatField(max_length=20, default="")
    Hemi_African_American = models.CharField(max_length=20, default="")
    Hemi_American = models.CharField(max_length=20, default="")
    Hemi_East_Asian = models.CharField(max_length=20, default="")
    Hemi_Finnish = models.CharField(max_length=20, default="")
    Hemi_Non_Finnish_European = models.CharField(max_length=20, default="")
    Hemi_Other = models.CharField(max_length=20, default="")
    Hemi_South_Asian = models.CharField(max_length=20, default="")
    Het_African_American = models.CharField(max_length=20, default="")
    Het_American = models.CharField(max_length=20, default="")
    Het_East_Asian = models.CharField(max_length=20, default="")
    Het_Finnish = models.CharField(max_length=20, default="")
    Het_Non_Finnish_European = models.CharField(max_length=20, default="")
    Het_Other = models.CharField(max_length=20, default="")
    Het_South_Asian = models.CharField(max_length=20, default="")
    Hom_African_American = models.BigIntegerField(default=0)
    Hom_American = models.BigIntegerField(default=0)
    Hom_East_Asian = models.BigIntegerField(default=0)
    Hom_Finnish = models.BigIntegerField(default=0)
    Hom_Non_Finnish_European_Homozygous = models.BigIntegerField(default=0)
    Hom_Other = models.BigIntegerField(default=0)
    Hom_South_Asian = models.BigIntegerField(default=0)
    InbreedingCoef = models.FloatField(max_length=100, default="")
    DP_HIST = models.CharField(max_length=1000, default="")
    GQ_HIST = models.CharField(max_length=1000, default="")

class Annotation(models.Model):
    Variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    Population = models.ForeignKey(Population, on_delete=models.CASCADE)
    Allele = models.CharField(max_length=20, default="")
    Consequence = models.CharField(max_length=100, default="")
    Impact = models.CharField(max_length=100, default="")
    Gene_Symbol = models.CharField(max_length=20, default="")
    Gene = models.CharField(max_length=100, default="")
    Feature = models.CharField(max_length=100, default="")
    Feature_type = models.CharField(max_length=100, default="")
    Biotype = models.CharField(max_length=100, default="")
    Exon = models.CharField(max_length=100, default="")
    Intron = models.CharField(max_length=100, default="")
    HGVS_DNA = models.CharField(max_length=100, default="")
    HGVS_Protein = models.CharField(max_length=100, default="")
    cDNA_position = models.CharField(max_length=100, default="")
    CDS_position = models.CharField(max_length=100, default="")
    Protein_position = models.CharField(max_length=100, default="")
    Amino_acids = models.CharField(max_length=100, default="")
    Codons = models.CharField(max_length=100, default="")
    Existing_variation = models.CharField(max_length=100, default="")
    ALLELE_NUM = models.BigIntegerField(default=0)
    DISTANCE = models.BigIntegerField(default=0)
    STRAND = models.BigIntegerField(default=0)
    VARIANT_CLASS = models.CharField(max_length=100, default="")
    MINIMISED = models.BigIntegerField(default=0)
    SYMBOL_SOURCE = models.CharField(max_length=100, default="")
    HGNC_ID = models.BigIntegerField(default=0)
    CANONICAL = models.CharField(max_length=5, default="")
    TSL = models.CharField(max_length=100, default="")
    CCDS = models.CharField(max_length=100, default="")
    ENSP = models.CharField(max_length=100, default="")
    SWISSPROT = models.CharField(max_length=100, default="")
    TREMBL = models.CharField(max_length=100, default="")
    UNIPARC = models.CharField(max_length=100, default="")
    SIFT = models.CharField(max_length=100, default="")
    PolyPhen = models.CharField(max_length=100, default="")
    DOMAINS = models.CharField(max_length=100, default="")
    HGVS_OFFSET = models.BigIntegerField(default=0)
    GMAF = models.CharField(max_length=100, default="")
    AFR_MAF = models.CharField(max_length=10, default="")
    AMR_MAF = models.CharField(max_length=10, default="")
    ASN_MAF = models.CharField(max_length=10, default="")
    EAS_MAF = models.CharField(max_length=10, default="")
    EUR_MAF = models.CharField(max_length=10, default="")
    SAS_MAF = models.CharField(max_length=10, default="")
    AA_MAF = models.CharField(max_length=10, default="")
    EA_MAF = models.CharField(max_length=10, default="")
    CLIN_SIG = models.CharField(max_length=10, default="")
    SOMATIC = models.CharField(max_length=10, default="")
    PHENO = models.CharField(max_length=10, default="")
    PUBMED = models.CharField(max_length=10, default="")
    MOTIF_NAME = models.CharField(max_length=10, default="")
    MOTIF_POS = models.BigIntegerField(default=0)
    HIGH_INF_POS = models.CharField(max_length=10, default="")
    MOTIF_SCORE_CHANGE = models.FloatField(max_length=10, default="")
    LoF_info = models.CharField(max_length=10, default="")
    LoF_flags = models.CharField(max_length=10, default="")
    LoF_filter = models.CharField(max_length=10, default="")
    LoF = models.CharField(max_length=10, default="")
    context = models.CharField(max_length=10, default="")
    ancestral = models.CharField(max_length=10, default="")